# Generated by Django 3.2.1 on 2024-01-30 11:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Portfolio', max_length=100)),
                ('description', models.CharField(default='My Portfolio', max_length=200)),
                ('keywords', models.CharField(default='portfolio, resume, cv', max_length=200)),
                ('author', models.CharField(default='Hamza Hassanain', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('url', models.URLField(default='https://hamzahassanain.onrender.com')),
                ('site_name', models.CharField(default='Hamza Hassanain Resume', max_length=100)),
                ('type', models.CharField(default='website', max_length=100)),
                ('twitter_creator', models.CharField(default='@hamzahasa067', max_length=100)),
            ],
        ),
    ]
