# Generated by Django 3.2.1 on 2024-01-30 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
