# Generated by Django 3.2.1 on 2024-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20240128_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='priority',
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experiencecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
