# Generated by Django 3.2.1 on 2024-01-28 09:50

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20240128_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecategory',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
    ]
