# Generated by Django 3.2.1 on 2024-01-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experiencecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
