# Generated by Django 3.2.1 on 2024-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_alter_experiencecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
