# Generated by Django 3.2.1 on 2024-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillscategory',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
