# Generated by Django 3.2.1 on 2024-01-28 10:04

import cloudinary.models
from django.db import migrations, models
import personal_projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('small_description', models.TextField(blank=True)),
                ('description', personal_projects.models.BigTextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
            ],
        ),
    ]
