# Generated by Django 5.0.1 on 2024-01-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BladeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('blad_icon_code', models.CharField(max_length=100)),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
            ],
        ),
    ]
