# Generated by Django 3.2.1 on 2024-01-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_rename_blad_icon_code_bladeicon_blade_icon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('icon_code', models.CharField(max_length=100)),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
            ],
        ),
        migrations.DeleteModel(
            name='BladeIcon',
        ),
    ]
